apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: voice-assistant
data:
  init.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE DATABASE azizzakiryarov;
      GRANT ALL PRIVILEGES ON DATABASE azizzakiryarov TO $POSTGRES_USER;
    EOSQL