apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-assistant-deployment-frontend
  namespace: voice-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-assistant
      tier: frontend
  template:
    metadata:
      labels:
        app: voice-assistant
        tier: frontend
    spec:
      containers:
        - name: voice-assistant
          image: azizzakiryarov/voice-assistant-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
