apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-assistant-deployment-frontend
  namespace: voice-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-assistant
      tier: frontend
  template:
    metadata:
      labels:
        app: voice-assistant
        tier: frontend
    spec:
      containers:
        - name: voice-assistant
          image: azizzakiryarov/voice-assistant-frontend:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sed -i 's|T.post("/text",n)|T.post("/todos",n)|g' /usr/share/nginx/html/js/*.js
          ports:
            - containerPort: 80
