apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-assistant-ingress
  namespace: voice-assistant
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Ändra till "true" om du aktiverar HTTPS senare
spec:
  rules:
    - host: raspberrypi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voice-assistant-service-frontend
                port:
                  number: 80