apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-assistant-ingress-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voice-assistant-service-frontend
                port:
                  number: 5173