ingress:
  localHosts:
    - raspberrypi.local
  hosts:
    - voice-assistant.duckdns.org
  tls:
    enabled: true
    secretName: voice-assistant-duckdns-tls
    hosts:
      - voice-assistant.duckdns.org

certManager:
  clusterIssuer:
    enabled: true
    name: letsencrypt-prod
    email: zakiryarov@hotmail.com

app:
  frontendUrl: https://voice-assistant.duckdns.org/
