apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-assistant-ci-cache
  namespace: voice-assistant-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-assistant-ci-source
  namespace: voice-assistant-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
