apiVersion: v1
kind: Service
metadata:
  name: voice-assistant-service-backend
spec:
  selector:
    app: voice-assistant
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP