apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: voice-assistant
type: Opaque
data:
  postgres-user: YXppenpha2lyeWFyb3Y=
  postgres-password: cGFzc3dvcmQ=
  postgres-db: dm9pY2Vhc3Npc3RhbnQ=