apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: voice-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: azizzakiryarov/local-whisper-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: WHISPER_MODEL
              value: "small"
            - name: WHISPER_HOTWORDS
              value: "Boka ett möte med Peter Andersson den trettonde juni den 13 juni klockan tio noll noll kl 10 00"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
